"use strict";

window.DORJE_DROLO_CONTENT = {
  audioRoot: "media/",
  source: {
    title: "The Perfectly Clear Path to Liberation",
    subtitle: "The Foundational Practice Liturgy of Dorje Drolö, the Heart Essence of the Primordial Secret",
    author: "Khenpo Karma Ratna",
    version: "2.0",
    copyright: "© 2025 Tergar International. Some rights reserved.",
    translators: "Translated by Cortland Dahl and Michele Martin. Tibetan and phonetics by Altaír Peredo.",
    licence: "Creative Commons Attribution-NonCommercial-NoDerivatives 3.0 US",
    file: "media/Dorje%20Drolo%20Ngondro%20Liturgy-Final%20(04-25)2.0-en_US.pdf",
  },
  dailySource: {
    title: "Tergar Daily Chants",
    edition: "22 May 2026 edition",
    publisher: "Tergar Asia Foundation",
    file: "media/Tergar%20Daily%20Chants%202026.pdf",
    publicUrl: "https://hk.tergarasia.org/wp-content/uploads/2026/06/Daily-chants-20260522.pdf",
  },
  groups: [
    { id: "daily", title: "Tergar daily chants" },
    { id: "opening", title: "Opening" },
    { id: "six-thoughts", title: "The six thoughts" },
    { id: "refuge", title: "Refuge & bodhichitta" },
    { id: "lineage", title: "Lineage" },
    { id: "dedication", title: "Dedication" },
  ],
  tracks: [
    { id: "daily-refuge", group: "daily", title: "Refuge and Bodhichitta", subtitle: "Tergar daily chant", file: "refuge and boddhicitta.mp3", duration: "1:10", transcript: "daily-refuge", readerLabel: "Daily refuge" },
    { id: "four-immeasurables", group: "daily", title: "Four Immeasurables", file: "Four immeasurables.mp3", duration: "2:07", transcript: "four-immeasurables", readerLabel: "Immeasurables" },
    { id: "kagyu-lineage", group: "lineage", title: "Supplication to the Kagyu Lineage", file: "Supplication to Kagyu Lineage.mp3", duration: "3:35", transcript: "kagyu-lineage", readerLabel: "Kagyü prayer" },
    { id: "request-blessing", group: "opening", title: "Request for Blessings", file: "RequestBlessing.mp3", duration: "0:54" },
    { id: "seven-branch", group: "opening", title: "Seven Branch Prayer", file: "7Br-Main.mp3", duration: "0:55" },
    { id: "reflection-one", group: "six-thoughts", title: "First Reflection", subtitle: "Beginningless samsara", file: "First Reflection.mp3", duration: "0:29", transcript: "reflection-one" },
    { id: "reflection-two", group: "six-thoughts", title: "Second Reflection", subtitle: "Precious human existence", file: "Second Reflection - Precious Human Existence.mp3", duration: "0:23", transcript: "reflection-two" },
    { id: "reflection-three", group: "six-thoughts", title: "Third Reflection", subtitle: "Impermanence", file: "Third Reflection - Impermanence.mp3", duration: "0:25", transcript: "reflection-three" },
    { id: "reflection-four", group: "six-thoughts", title: "Fourth Reflection", subtitle: "Karma", file: "Fourth Reflection - Karma.mp3", duration: "0:26", transcript: "reflection-four" },
    { id: "reflection-five", group: "six-thoughts", title: "Fifth Reflection", subtitle: "Suffering of samsara", file: "Fifth Reflection - Suffering of Samsara.mp3", duration: "0:24", transcript: "reflection-five" },
    { id: "reflection-six", group: "six-thoughts", title: "Sixth Reflection", subtitle: "Benefits of liberation", file: "Sixth Reflection - Liberation.mp3", duration: "0:24", transcript: "reflection-six" },
    { id: "refuge-main", group: "refuge", title: "Refuge and Bodhichitta", subtitle: "Dorje Drolö", file: "Refuge and Boddhicitta - Dorje Drolo.mp3", duration: "0:51" },
    { id: "refuge-second", group: "refuge", title: "Refuge and Bodhichitta II", subtitle: "Dorje Drolö, extended recording", file: "Refuge and Boddhicitta 2 - Droje Drolo.mp3", duration: "1:47" },
    { id: "prostration-short", group: "refuge", title: "Prostration Refuge Prayer", subtitle: "short recording", file: "Prostration Short Refuge Prayer.mp3", duration: "0:48" },
    { id: "prostration-super-short", group: "refuge", title: "Prostration Refuge Prayer", subtitle: "very short recording", file: "RefProSuperShort.mp3", duration: "0:08" },
    { id: "generate-bodhichitta", group: "refuge", title: "Generating Bodhichitta", file: "GenBodhich.mp3", duration: "1:57" },
    { id: "dedication-aspiration", group: "dedication", title: "Dedication and Aspiration", file: "DedAspiration.mp3", duration: "1:27" },
    { id: "dedication-prayers", group: "dedication", title: "Dedication Prayers", subtitle: "Tergar daily closing chant", file: "DedPrayers.mp3", duration: "0:26", transcript: "dedication-prayers", readerLabel: "Daily dedication" },
  ],
  practiceSteps: [
    { id: "daily-refuge", part: "Tergar daily opening", title: "Refuge and bodhicitta", kind: "track", trackId: "daily-refuge" },
    { id: "daily-four-immeasurables", part: "Tergar daily opening", title: "Four immeasurables", kind: "track", trackId: "four-immeasurables" },
    { id: "daily-kagyu-supplication", part: "Tergar daily opening", title: "Supplication to the Kagyu lineage", kind: "track", trackId: "kagyu-lineage" },
    { id: "nine-breaths", part: "Preparation", title: "Nine breaths", subtitle: "Removing stale air", kind: "manual", note: "Practice the nine breaths in your usual way. Continue when you are ready." },
    { id: "main-opening", part: "Dorje Drolö liturgy", title: "Opening passage", kind: "choice", trackIds: ["request-blessing", "seven-branch"], note: "The two available opening recordings are here for selection while the exact boundary of your ‘opening bit’ is checked." },
    { id: "reflection-one", part: "Six thoughts", title: "First reflection", subtitle: "Beginningless samsara", kind: "track", trackId: "reflection-one" },
    { id: "reflection-two", part: "Six thoughts", title: "Second reflection", subtitle: "Precious human existence", kind: "track", trackId: "reflection-two" },
    { id: "reflection-three", part: "Six thoughts", title: "Third reflection", subtitle: "Impermanence", kind: "track", trackId: "reflection-three" },
    { id: "reflection-four", part: "Six thoughts", title: "Fourth reflection", subtitle: "Karma", kind: "track", trackId: "reflection-four" },
    { id: "reflection-five", part: "Six thoughts", title: "Fifth reflection", subtitle: "Suffering of samsara", kind: "track", trackId: "reflection-five" },
    { id: "reflection-six", part: "Six thoughts", title: "Sixth reflection", subtitle: "Benefits of liberation", kind: "track", trackId: "reflection-six" },
    { id: "refuge-opening", part: "Dorje Drolö refuge", title: "Refuge opening", kind: "track", trackId: "refuge-main", review: true },
    { id: "prostrations", part: "Dorje Drolö refuge", title: "Prostration section", subtitle: "Om Ah Hung", kind: "choice", trackIds: ["prostration-short", "prostration-super-short"], counter: true },
    { id: "refuge-remainder", part: "Dorje Drolö refuge", title: "Remainder of refuge", kind: "track", trackId: "refuge-second", review: true },
    { id: "main-bodhichitta", part: "Dorje Drolö liturgy", title: "Bodhichitta", kind: "track", trackId: "generate-bodhichitta", review: true },
    { id: "open-awareness", part: "Main practice", title: "Open awareness", subtitle: "Nature of mind practice", kind: "manual", note: "Rest in open awareness in your usual way. Continue when you are ready." },
    { id: "shaking-ha", part: "Main practice", title: "Shaking / Ha practice", kind: "manual", note: "Do the shaking / Ha practice in your usual way. Continue when you are ready." },
    { id: "main-dedication", part: "Dorje Drolö closing", title: "Aspiration and dedication", kind: "track", trackId: "dedication-aspiration", review: true },
    { id: "daily-dedication", part: "Tergar daily closing", title: "Dedication", kind: "track", trackId: "dedication-prayers", review: true },
  ],
  transcripts: {
    "daily-refuge": {
      title: "Refuge and Bodhichitta",
      subtitle: "Tergar Daily Chants",
      sourcePage: "Tergar Daily Chants, printed page 9 (PDF page 6)",
      status: "Three recitations aligned to the recording; review while listening.",
      phrases: [
        {
          start: 7.642,
          end: 13.0,
          marker: "Recitation 1",
          tibetan: "སངས་རྒྱས་ཆོས་དང་ཚོགས་ཀྱི་མཆོག་རྣམས་ལ། །",
          phonetics: "SANG GYEY CHÖ TANG TSOKE KYEE CHOKE NAM LA",
          english: ["In the Buddha, Dharma and Supreme Assembly,"],
        },
        {
          start: 13.4,
          end: 17.988,
          tibetan: "བྱང་ཆུབ་བར་དུ་བདག་ནི་སྐྱབས་སུ་མཆི། །",
          phonetics: "CHANG CHUPE PAR DU DAK NEE KYAP SU CHEE",
          english: ["I take refuge until enlightenment is achieved."],
        },
        {
          start: 18.43,
          end: 23.005,
          tibetan: "བདག་གི་སྦྱིན་སོགས་བགྱིས་པའི་བསོད་ནམ་ཀྱིས། །",
          phonetics: "DAK KEY JIN SOKE GYEE PEY SÖNAM KYEE",
          english: ["May the merit of my generosity and other virtuous deeds"],
        },
        {
          start: 23.451,
          end: 29.15,
          tibetan: "འགྲོ་ལ་ཕན་ཕྱིར་སངས་རྒྱས་འགྲུབ་པར་ཤོག །",
          phonetics: "DRO LA PEN CHEER SANG GYEY DRUPE PAR SHOKE",
          english: ["Lead to buddhahood for the welfare of all beings."],
        },
        {
          start: 29.485,
          end: 34.476,
          marker: "Recitation 2",
          tibetan: "སངས་རྒྱས་ཆོས་དང་ཚོགས་ཀྱི་མཆོག་རྣམས་ལ། །",
          phonetics: "SANG GYEY CHÖ TANG TSOKE KYEE CHOKE NAM LA",
          english: ["In the Buddha, Dharma and Supreme Assembly,"],
        },
        {
          start: 34.979,
          end: 39.796,
          tibetan: "བྱང་ཆུབ་བར་དུ་བདག་ནི་སྐྱབས་སུ་མཆི། །",
          phonetics: "CHANG CHUPE PAR DU DAK NEE KYAP SU CHEE",
          english: ["I take refuge until enlightenment is achieved."],
        },
        {
          start: 40.05,
          end: 45.471,
          tibetan: "བདག་གི་སྦྱིན་སོགས་བགྱིས་པའི་བསོད་ནམ་ཀྱིས། །",
          phonetics: "DAK KEY JIN SOKE GYEE PEY SÖNAM KYEE",
          english: ["May the merit of my generosity and other virtuous deeds"],
        },
        {
          start: 45.668,
          end: 51.647,
          tibetan: "འགྲོ་ལ་ཕན་ཕྱིར་སངས་རྒྱས་འགྲུབ་པར་ཤོག །",
          phonetics: "DRO LA PEN CHEER SANG GYEY DRUPE PAR SHOKE",
          english: ["Lead to buddhahood for the welfare of all beings."],
        },
        {
          start: 52.479,
          end: 58.916,
          marker: "Recitation 3",
          tibetan: "སངས་རྒྱས་ཆོས་དང་ཚོགས་ཀྱི་མཆོག་རྣམས་ལ། །",
          phonetics: "SANG GYEY CHÖ TANG TSOKE KYEE CHOKE NAM LA",
          english: ["In the Buddha, Dharma and Supreme Assembly,"],
        },
        {
          start: 59.358,
          end: 62.148,
          tibetan: "བྱང་ཆུབ་བར་དུ་བདག་ནི་སྐྱབས་སུ་མཆི། །",
          phonetics: "CHANG CHUPE PAR DU DAK NEE KYAP SU CHEE",
          english: ["I take refuge until enlightenment is achieved."],
        },
        {
          start: 62.904,
          end: 66.582,
          tibetan: "བདག་གི་སྦྱིན་སོགས་བགྱིས་པའི་བསོད་ནམ་ཀྱིས། །",
          phonetics: "DAK KEY JIN SOKE GYEE PEY SÖNAM KYEE",
          english: ["May the merit of my generosity and other virtuous deeds"],
        },
        {
          start: 66.962,
          end: 70.076,
          tibetan: "འགྲོ་ལ་ཕན་ཕྱིར་སངས་རྒྱས་འགྲུབ་པར་ཤོག །",
          phonetics: "DRO LA PEN CHEER SANG GYEY DRUPE PAR SHOKE",
          english: ["Lead to buddhahood for the welfare of all beings."],
        },
      ],
    },
    "four-immeasurables": {
      title: "The Four Immeasurables",
      subtitle: "Tergar Daily Chants",
      sourcePage: "Tergar Daily Chants, printed pages 10–11 (PDF page 7)",
      status: "Three recitations aligned to the recording; review while listening.",
      phrases: [
        {
          start: 3.112,
          end: 16.48,
          marker: "Recitation 1",
          tibetan: "སེམས་ཅན་ཐམས་ཅད་བདེ་བ་དང་བདེ་བའི་རྒྱུ་དང་ལྡན་པར་གྱུར་ཅིག །",
          phonetics: "SEM CHEN TOM CHEY DEY WA TANG DE WEY GYU TANG DEN PAR GYUR CHIK",
          english: ["May all sentient beings have happiness and its causes."],
        },
        {
          start: 16.729,
          end: 32.101,
          tibetan: "སྡུག་བསྔལ་དང་སྡུག་བསྔལ་གྱི་རྒྱུ་དང་བྲལ་བར་གྱུར་ཅིག །",
          phonetics: "DUKE NGEL TANG DUKE NGEL GYEE GYU TANG DREL WAR GYUR CHIK",
          english: ["May they be free from suffering and its causes."],
        },
        {
          start: 32.368,
          end: 45.718,
          tibetan: "སྡུག་བསྔལ་མེད་པའི་བདེ་བ་དམ་པ་དང་མི་འབྲལ་བར་གྱུར་ཅིག །",
          phonetics: "DUKE NGEL MEY PEY DEY WA TOM PA TANG ME DREL WAR GYUR CHIK",
          english: ["May they never be parted from sublime bliss, free from suffering."],
        },
        {
          start: 45.964,
          end: 61.959,
          tibetan: "ཉེ་རིང་ཆགས་སྡང་གཉིས་དང་བྲལ་བའི་བཏང་སྙོམས་ཆེན་པོ་ལ་གནས་པར་གྱུར་ཅིག །",
          phonetics: "NYEY RING CHAK DANG NYEE TANG DREL WEY TANG NYOME CHEN PO LA NEY PAR GYUR CHIK",
          english: ["May they dwell in great equanimity, free from attachment and", "aversion to those near and far."],
        },
        {
          start: 62.465,
          end: 74.482,
          marker: "Recitation 2",
          tibetan: "སེམས་ཅན་ཐམས་ཅད་བདེ་བ་དང་བདེ་བའི་རྒྱུ་དང་ལྡན་པར་གྱུར་ཅིག །",
          phonetics: "SEM CHEN TOM CHEY DEY WA TANG DE WEY GYU TANG DEN PAR GYUR CHIK",
          english: ["May all sentient beings have happiness and its causes."],
        },
        {
          start: 75.143,
          end: 81.605,
          tibetan: "སྡུག་བསྔལ་དང་སྡུག་བསྔལ་གྱི་རྒྱུ་དང་བྲལ་བར་གྱུར་ཅིག །",
          phonetics: "DUKE NGEL TANG DUKE NGEL GYEE GYU TANG DREL WAR GYUR CHIK",
          english: ["May they be free from suffering and its causes."],
        },
        {
          start: 82.221,
          end: 90.621,
          tibetan: "སྡུག་བསྔལ་མེད་པའི་བདེ་བ་དམ་པ་དང་མི་འབྲལ་བར་གྱུར་ཅིག །",
          phonetics: "DUKE NGEL MEY PEY DEY WA TOM PA TANG ME DREL WAR GYUR CHIK",
          english: ["May they never be parted from sublime bliss, free from suffering."],
        },
        {
          start: 91.87,
          end: 102.039,
          tibetan: "ཉེ་རིང་ཆགས་སྡང་གཉིས་དང་བྲལ་བའི་བཏང་སྙོམས་ཆེན་པོ་ལ་གནས་པར་གྱུར་ཅིག །",
          phonetics: "NYEY RING CHAK DANG NYEE TANG DREL WEY TANG NYOME CHEN PO LA NEY PAR GYUR CHIK",
          english: ["May they dwell in great equanimity, free from attachment and", "aversion to those near and far."],
        },
        {
          start: 105.564,
          end: 109.011,
          marker: "Recitation 3",
          tibetan: "སེམས་ཅན་ཐམས་ཅད་བདེ་བ་དང་བདེ་བའི་རྒྱུ་དང་ལྡན་པར་གྱུར་ཅིག །",
          phonetics: "SEM CHEN TOM CHEY DEY WA TANG DE WEY GYU TANG DEN PAR GYUR CHIK",
          english: ["May all sentient beings have happiness and its causes."],
        },
        {
          start: 109.975,
          end: 113.148,
          tibetan: "སྡུག་བསྔལ་དང་སྡུག་བསྔལ་གྱི་རྒྱུ་དང་བྲལ་བར་གྱུར་ཅིག །",
          phonetics: "DUKE NGEL TANG DUKE NGEL GYEE GYU TANG DREL WAR GYUR CHIK",
          english: ["May they be free from suffering and its causes."],
        },
        {
          start: 114.547,
          end: 118.749,
          tibetan: "སྡུག་བསྔལ་མེད་པའི་བདེ་བ་དམ་པ་དང་མི་འབྲལ་བར་གྱུར་ཅིག །",
          phonetics: "DUKE NGEL MEY PEY DEY WA TOM PA TANG ME DREL WAR GYUR CHIK",
          english: ["May they never be parted from sublime bliss, free from suffering."],
        },
        {
          start: 119.751,
          end: 127.044,
          tibetan: "ཉེ་རིང་ཆགས་སྡང་གཉིས་དང་བྲལ་བའི་བཏང་སྙོམས་ཆེན་པོ་ལ་གནས་པར་གྱུར་ཅིག །",
          phonetics: "NYEY RING CHAK DANG NYEE TANG DREL WEY TANG NYOME CHEN PO LA NEY PAR GYUR CHIK",
          english: ["May they dwell in great equanimity, free from attachment and", "aversion to those near and far."],
        },
      ],
    },
    "kagyu-lineage": {
      title: "Supplication to the Dakpo Kagyü",
      subtitle: "Tergar Daily Chants",
      sourcePage: "Tergar Daily Chants, printed pages 2–7 (PDF pages 3–5)",
      status: "All 29 lines aligned to the recording cadence; review while listening.",
      phrases: [
        {
          start: 3.77,
          end: 10.97,
          tibetan: "རྡོ་རྗེ་འཆང་ཆེན་ཏཻ་ལོ་ནཱ་རོ་དང་། །",
          phonetics: "DOR JAY CHANG CHEN TE LO NA RO TANG",
          english: ["Great Vajradhara, Tilo, Naro,"],
        },
        {
          start: 11.49,
          end: 17.93,
          tibetan: "མར་པ་མི་ལ་ཆོས་རྗེ་སྒམ་པོ་པ། །",
          phonetics: "MAR PA MI LA CHÖ JAY GAM PO PA",
          english: ["Marpa, Mila, Lord of Dharma Gampopa,"],
        },
        {
          start: 18.55,
          end: 24.93,
          tibetan: "དུས་གསུམ་ཤེས་བྱ་ཀུན་མཁྱེན་ཀརྨ་པ། །",
          phonetics: "DÜ SUM SHEY CHA KÜN KHYEN KARMA PA",
          english: ["Knower of the three times, omniscient Karmapa,"],
        },
        {
          start: 25.53,
          end: 31.87,
          tibetan: "ཆེ་བཞི་ཆུང་བརྒྱད་བརྒྱུད་པ་འཛིན་རྣམས་དང་། །",
          phonetics: "CHEY SHI CHUNG GYAY GYÜ PA DZIN NAM TANG",
          english: ["Holders of the four great and eight minor lineages:"],
        },
        {
          start: 32.45,
          end: 38.83,
          tibetan: "འབྲི་སྟག་ཚལ་གསུམ་དཔལ་ལྡན་འབྲུག་པ་སོགས། །",
          phonetics: "DRI TAK TSAL SUM PEL DEN DRUK PA SOKE",
          english: ["Drikung, Taklung, Tsalpa, glorious Drukpa, and so on,"],
        },
        {
          start: 39.37,
          end: 45.67,
          tibetan: "ཟབ་ལམ་ཕྱག་རྒྱ་ཆེ་ལ་མངའ་བརྙེས་པའི། །",
          phonetics: "SAP LAM CHAK GYA CHAY LA NGA NYAY PAY",
          english: ["Masters of the profound path of Mahamudra –"],
        },
        {
          start: 46.31,
          end: 52.59,
          tibetan: "མཉམ་མེད་འགྲོ་མགོན་དྭགས་པོ་བཀའ་བརྒྱུད་ལ། །",
          phonetics: "NYAM MEY DRO GÖN DAK PO KA GYÜ LA",
          english: ["Peerless protectors of beings, the Dakpo Kagyü,"],
        },
        {
          start: 53.13,
          end: 59.51,
          tibetan: "གསོལ་བ་འདེབས་སོ་བཀའ་བརྒྱུད་བླ་མ་རྣམས། །",
          phonetics: "SÖL WA DEP SO KA GYÜ LA MA NAM",
          english: ["I pray to you, Kagyü Gurus; I hold your lineage."],
        },
        {
          start: 60.09,
          end: 66.49,
          tibetan: "བརྒྱུད་པ་འཛིན་ནོ་རྣམ་ཐར་བྱིན་གྱིས་རློབས། །",
          phonetics: "GYÜ PA DZIN NO NAM TAR CHIN GYI LOPE",
          english: ["Grant your blessings that I may follow your example."],
        },
        {
          start: 67.05,
          end: 73.45,
          tibetan: "ཞེན་ལོག་སྒོམ་གྱི་རྐང་པར་གསུངས་པ་བཞིན། །",
          phonetics: "SHEN LOKE GOME GYI KANG PAR SUNG PA SHIN",
          english: ["Revulsion is the foot of meditation, as is taught."],
        },
        {
          start: 74.13,
          end: 80.47,
          tibetan: "ཟས་ནོར་ཀུན་ལ་ཆགས་ཞེན་མེད་པ་དང་། །",
          phonetics: "SAY NOR KÜN LA CHAK SHEN MAY PA TANG",
          english: ["Please bless this meditator who cuts all ties to this life,"],
        },
        {
          start: 81.03,
          end: 87.37,
          tibetan: "ཚེ་འདིའི་གདོས་ཐག་ཆོད་པའི་སྒོམ་ཆེན་ལ། །",
          phonetics: "TSEY DEER DÖ TAK CHÖ PAY GOM CHEN LA",
          english: ["Who is not obsessed with food and wealth:"],
        },
        {
          start: 87.95,
          end: 94.29,
          tibetan: "རྙེད་བཀུར་ཞེན་པ་མེད་པར་བྱིན་གྱིས་རློབས། །",
          phonetics: "NYE KUR SHEN PA MAY PAR CHIN GYI LOPE",
          english: ["May I be unattached to praise and gain."],
        },
        {
          start: 94.83,
          end: 101.33,
          tibetan: "མོས་གུས་སྒོམ་གྱི་མགོ་བོར་གསུངས་པ་བཞིན། །",
          phonetics: "MÖ GÖ GOM GYI GO WOR SUNG PA SHIN",
          english: ["Devotion is the head of meditation, as is taught."],
        },
        {
          start: 101.93,
          end: 108.31,
          tibetan: "མན་ངག་གཏེར་སྒོ་འབྱེད་པའི་བླ་མ་ལ། །",
          phonetics: "MEN NGAK TER GO JAY PAY LA MA LA",
          english: ["Please bless this meditator who always prays"],
        },
        {
          start: 108.79,
          end: 115.11,
          tibetan: "རྒྱུན་དུ་གསོལ་བ་འདེབས་པའི་སྒོམ་ཆེན་ལ། །",
          phonetics: "GYÜN TU SÖL WA DEP PAY GOM CHEN LA",
          english: ["To the guru who reveals the treasury of key instructions:"],
        },
        {
          start: 116.23,
          end: 122.61,
          tibetan: "བཅོས་མིན་མོས་གུས་སྐྱེ་བར་བྱིན་གྱིས་རློབས། །",
          phonetics: "CHÖ MIN MÖ GÜ KYE WAR CHIN GYI LOPE",
          english: ["May genuine devotion be born in me."],
        },
        {
          start: 123.09,
          end: 129.43,
          tibetan: "ཡེངས་མེད་སྒོམ་གྱི་དངོས་གཞིར་གསུངས་པ་བཞིན་། །",
          phonetics: "YENG MAY GOMGYI NGÖ SHEER SUNG PA SHIN",
          english: ["Non-distraction is the main practice of meditation, as is taught."],
        },
        {
          start: 130.05,
          end: 136.19,
          tibetan: "གང་ཤར་རྟོག་པའི་ངོ་བོ་སོ་མ་དེ། །",
          phonetics: "GANG SHAR TOKE PAY NGO WO SO MA TAY",
          english: ["Please bless this meditator who rests directly, without fabrication,"],
        },
        {
          start: 136.67,
          end: 142.97,
          tibetan: "མ་བཅོས་དེ་ཀར་འཇོག་པའི་སྒོམ་ཆེན་ལ། །",
          phonetics: "MA CHÖ TAY KAR JOKE PAY GOM CHEN LA",
          english: ["In the fresh essence of whatever thoughts arise:"],
        },
        {
          start: 143.53,
          end: 149.83,
          tibetan: "བསྒོམ་བྱ་བློ་དང་བྲལ་བར་བྱིན་གྱིས་རློབས། །",
          phonetics: "GOM CHA LO TANG DREL WAR CHIN GYI LOPE",
          english: ["May my meditation be free from conceptual mind."],
        },
        {
          start: 151.01,
          end: 157.19,
          tibetan: "རྣམ་རྟོག་ངོ་བོ་ཆོས་སྐུར་གསུངས་པ་བཞིན། །",
          phonetics: "NAM TOKE NGO WOR CHÖ KUR SUNG PA SHIN",
          english: ["The essence of thoughts is dharmakaya, as is taught."],
        },
        {
          start: 157.91,
          end: 164.23,
          tibetan: "ཅི་ཡང་མ་ཡིན་ཅིར་ཡང་འཆར་བ་ལ། །",
          phonetics: "CHEE YANG MA YIN CHEER YANG CHAR WA LA",
          english: ["It is nothing at all, yet can manifest as anything."],
        },
        {
          start: 164.75,
          end: 171.13,
          tibetan: "མ་འགགས་རོལ་པར་འཆར་བའི་སྒོམ་ཆེན་ལ། །",
          phonetics: "MA GAK RÖL PAR CHAR WAY GOM CHEN LA",
          english: ["Please bless this meditator who manifests in unimpeded display:"],
        },
        {
          start: 171.73,
          end: 178.23,
          tibetan: "འཁོར་འདས་དབྱེར་མེད་རྟོགས་པར་བྱིན་གྱིས་རློབས། །",
          phonetics: "KOR DAY YER MAY TOKE PAR CHIN GYI LOPE",
          english: ["May I realize the inseparability of samsara and nirvana."],
        },
        {
          start: 178.75,
          end: 184.99,
          tibetan: "སྐྱེ་བ་ཀུན་ཏུ་ཡང་དག་བླ་མ་དང་། །",
          phonetics: "KYE WA KÜN TU YANG TAK LA MA TANG",
          english: ["In all lives, may I not be parted from my true guru,"],
        },
        {
          start: 185.61,
          end: 192.05,
          tibetan: "འབྲལ་མེད་ཆོས་ཀྱི་དཔལ་ལ་ལོངས་སྤྱོད་ཅིང་། །",
          phonetics: "DREL MAY CHÖ KYI PEL LA LONG CHÖ CHING",
          english: ["Forever enjoying the richness of Dharma."],
        },
        {
          start: 192.57,
          end: 198.97,
          tibetan: "ས་དང་ལམ་གྱི་ཡོན་ཏན་རབ་རྫོགས་ནས། །",
          phonetics: "SA TANG LAM GYI YÖN TEN RAP DZOKE NAY",
          english: ["Perfecting the qualities of the paths and levels,"],
        },
        {
          start: 199.55,
          end: 206.05,
          tibetan: "རྡོ་རྗེ་འཆང་གི་གོ་འཕང་མྱུར་ཐོབ་ཤོག །",
          phonetics: "DOR JAY CHANG KEE KO PANG NYUR TOPE SHOK",
          english: ["May I swiftly attain the state of Vajradhara."],
        },
      ],
    },
    "dedication-prayers": {
      title: "Dedication Prayers",
      subtitle: "Tergar Daily Chants",
      sourcePage: "Tergar Daily Chants, printed pages 30–31 (PDF page 17)",
      status: "Four lines aligned to the recording pauses; review while listening.",
      phrases: [
        {
          start: 0.25,
          end: 6.01,
          tibetan: "བསོད་ནམས་འདི་ཡིས་ཐམས་ཅད་གཟིགས་པ་ཉིད། །",
          phonetics: "SÖ NAM DEE YEE TOM CHEY ZIK PA NYEE",
          english: ["By this merit, may all attain omniscience"],
        },
        {
          start: 7.19,
          end: 11.31,
          tibetan: "ཐོབ་ནས་ཉེས་པའི་དགྲ་རྣམས་ཕམ་བྱས་ནས། །",
          phonetics: "TOPE NEY NYEY PEY DRA NAM PAM CHEY TEY",
          english: ["And defeat the enemy, wrong-doing."],
        },
        {
          start: 12.91,
          end: 16.65,
          tibetan: "སྐྱེ་རྒ་ན་འཆིའི་རྦ་རླབས་འཁྲུགས་པ་ཡི། །",
          phonetics: "KYEY GA NA CHEE BA LAB TRUKE PA YEE",
          english: ["From the stormy waves of birth, old age, sickness and death,"],
        },
        {
          start: 17.87,
          end: 24.47,
          tibetan: "སྲིད་པའི་མཚོ་ལས་འགྲོ་བ་སྒྲོལ་བར་ཤོགས། །",
          phonetics: "SEE PEY TSO LEY DRO WA DROLE WAR SHOKE",
          english: ["From the ocean of existence, may all beings be free."],
        },
      ],
    },
    "reflection-one": {
      title: "First Reflection",
      subtitle: "Beginningless samsara",
      sourcePage: "Liturgy page 3 (PDF page 5)",
      status: "Pilot timing derived from phrase pauses; review while listening.",
      phrases: [
        {
          start: 0.558,
          end: 6.692,
          tibetan: "ཀྱེ་མ་ཀྱེ་ཧུད་སྔོན་ཚེ་ཐོག་མེད་ནས།།",
          phonetics: "KYÉ MA KYÉ HÜ NGÖN TSÉ TOK MÉ NE",
          english: ["Alas! How sad!", "Through all my lives from beginningless time,"],
        },
        {
          start: 7.238,
          end: 11.645,
          tibetan: "འཁོར་བའི་རྒྱ་མཚོ་ཆེན་པོ་འཁྱམས་གྱུར་ཏེ།།",
          phonetics: "KOR WÉ GYA TSO CHEN PO KYAM GYUR TÉ",
          english: ["I have wandered this vast ocean of samsara."],
        },
        {
          start: 12.18,
          end: 16.723,
          tibetan: "ཤ་རུས་བསགས་ན་འཇིག་རྟེན་ཁམས་དང་མཉམ།།",
          phonetics: "SHA RÜ SAK NA JIK TEN KAM DANG NYAM",
          english: ["The flesh and bones of my bodies", "Could cover the entire world."],
        },
        {
          start: 17.269,
          end: 21.695,
          tibetan: "རྣག་ཁྲག་མཐའ་ཡི་རྒྱ་མཚོ་བས་ཀྱང་མང་།།",
          phonetics: "NAK TRAK TA YI GYA TSO WÉ KYANG MANG",
          english: ["Its fluids could fill an ocean."],
        },
        {
          start: 22.259,
          end: 28.264,
          tibetan: "དེ་བསམ་སྐྱོ་ཤས་སྐྱེ་བར་དཀོན་མཆོག་མཁྱེན།།",
          phonetics: "DÉ SAM KYO SHÉ KYÉ WAR KÖN CHOK KYEN",
          english: ["Pondering this brings me sorrow.", "Think of me, O Three Jewels."],
        },
      ],
    },
    "reflection-two": {
      title: "Second Reflection",
      subtitle: "Precious human existence",
      sourcePage: "Liturgy page 4 (PDF page 6)",
      status: "Phrase timing derived from pauses; review while listening.",
      phrases: [
        {
          start: 1.124,
          end: 6.186,
          tibetan: "ད་རེས་ལན་གཅིག་དལ་འབྱོར་ཐོབ་དུས་འདིར།།",
          phonetics: "TA RÉ LEN CHIK TEL JOR TOP DÜ DIR",
          english: ["Now that I have the freedoms", "And riches attained at long last,"],
        },
        {
          start: 6.684,
          end: 12.248,
          tibetan: "དོན་མེད་མི་ཚེ་སྟོང་ཟད་རོ་ཉལ་མཁན།།",
          phonetics: "TÖN MÉ MI TSÉ TONG ZÉ RO NYEL KEN",
          english: ["I must not miss the point of this life,", "And waste it, lying idle like a corpse,"],
        },
        {
          start: 12.719,
          end: 16.793,
          tibetan: "ཆོས་མེད་སྡིག་ལ་སྤྱོད་པ་ངོ་རེ་ཚ།།",
          phonetics: "CHÖ MÉ DIK LA CHÖ PA NGO RÉ TSA",
          english: ["Doing non-dharmic, negative things.", "Oh, what a shame!"],
        },
        {
          start: 17.271,
          end: 23.018,
          tibetan: "དལ་འབྱོར་དོན་ཡོད་ནུས་པར་དཀོན་མཆོག་མཁྱེན།།",
          phonetics: "TEL JOR DÖN YÖ NÜ PAR KÖN CHOK KYEN",
          english: ["Think of me, Three Jewels.", "May I bring meaning to these freedoms and riches."],
        },
      ],
    },
    "reflection-three": {
      title: "Third Reflection",
      subtitle: "Impermanence",
      sourcePage: "Liturgy pages 4–5 (PDF pages 6–7)",
      status: "Phrase timing derived from pauses; review while listening.",
      phrases: [
        {
          start: 0.389,
          end: 4.84,
          tibetan: "ལོ་ཟླ་ཞག་རེར་སོང་བཞིན་ལུས་ནི་རྒས།།",
          phonetics: "LO DA SHAK RER SONG SHIN LÜ NI GÉ",
          english: ["With each passing day, month, and year,", "This body of mine grows older."],
        },
        {
          start: 5.111,
          end: 9.129,
          tibetan: "སྐད་ཅིག་རེ་རེ་བཞིན་ཡང་མི་ཚེ་ཟད།།",
          phonetics: "KÉ CHIK RÉ RÉ SHIN YANG MI TSÉ SÉ",
          english: ["Moment by moment, my life ebbs away."],
        },
        {
          start: 9.658,
          end: 13.665,
          tibetan: "གཅིག་ཤི་གཉིས་ཤི་རེས་མོས་རང་ལ་བབ།།",
          phonetics: "CHIK SHI NYI SHI RÉ MÖ RANG LA PAP",
          english: ["One person dies, then another.", "Soon my turn will come."],
        },
        {
          start: 14.179,
          end: 18.305,
          tibetan: "འཆི་མེད་ལུང་བསྟན་ཐོབ་པ་མ་ཡིན་ནམ།།",
          phonetics: "CHI MÉ LUNG TEN TOP PA MA YIN NAM",
          english: ["I have not been foretold to be immortal."],
        },
        {
          start: 18.848,
          end: 24.673,
          tibetan: "མི་རྟག་རྒྱུད་ལ་སྐྱེས་པར་དཀོན་མཆོག་མཁྱེན།།",
          phonetics: "MI TAK GYU LA KYÉ PAR KÖN CHOK KYEN",
          english: ["Think of me, Three Jewels.", "May impermanence take birth in my being."],
        },
      ],
    },
    "reflection-four": {
      title: "Fourth Reflection",
      subtitle: "Karma",
      sourcePage: "Liturgy pages 5–6 (PDF pages 7–8)",
      status: "Phrase timing derived from pauses; review while listening.",
      phrases: [
        {
          start: 1.319,
          end: 6.71,
          tibetan: "དགེ་ལས་བདེ་བ་སྡིག་ལས་སྡུག་བསྔལ་གྱིས།།",
          phonetics: "GÉ LÉ DÉ WA DIK LÉ DUK NGEL GYI",
          english: ["Happiness comes from virtue", "And suffering from misdeeds."],
        },
        {
          start: 7.05,
          end: 10.996,
          tibetan: "འབྲས་བུ་འབྱུང་བ་མངོན་སུམ་གསལ་བཞིན་དུ།།",
          phonetics: "DRÉ BU CHUNG WA NGÖN SUM SEL SHIN DU",
          english: ["I can see these results appear clearly,"],
        },
        {
          start: 11.457,
          end: 15.438,
          tibetan: "ལས་འབྲས་མི་རྩི་ཁྱད་གསོད་སྙིང་སྲན་ཅན།།",
          phonetics: "LÉ DRÉ MI TSÉ KYÉ SÖ NYI SEN CHEN",
          english: ["Yet since my heart has hardened,", "I disregard the law of karma."],
        },
        {
          start: 15.874,
          end: 19.875,
          tibetan: "ད་ནི་དགེ་བ་བསྒྲུབ་ན་མི་འཐད་དམ།།",
          phonetics: "TA NI GÉ WA DRUP NA MI TÉ TAM",
          english: ["Should I not now practice virtue?"],
        },
        {
          start: 20.408,
          end: 26.061,
          tibetan: "བླང་དོར་ཚུལ་བཞིན་ནུས་པར་དཀོན་མཆོག་མཁྱེན།།",
          phonetics: "LANG DOR TSUL SHIN NÜ PAR KÖN CHOK KYEN",
          english: ["Think of me, Three Jewels.", "May I live an ethical life."],
        },
      ],
    },
    "reflection-five": {
      title: "Fifth Reflection",
      subtitle: "Suffering of samsara",
      sourcePage: "Liturgy page 6 (PDF page 8)",
      status: "Phrase timing derived from pauses; review while listening.",
      phrases: [
        {
          start: 0.501,
          end: 5.579,
          tibetan: "འགྲོ་བ་རིགས་དྲུག་གང་དུ་སྐྱེས་གྱུར་ཀྱང་།།",
          phonetics: "DRO WA RIK DRUK KANG DU KYÉ GYUR KYANG",
          english: ["No matter where I am born in the six realms,"],
        },
        {
          start: 5.991,
          end: 9.652,
          tibetan: "བདེ་བའི་གོ་སྐབས་སྐད་ཅིག་ཙམ་ཡང་མེད།།",
          phonetics: "DÉ WÉ KO KAP KÉ CHIK TSAM YANG MÉ",
          english: ["I won't find even a moment of happiness."],
        },
        {
          start: 10.098,
          end: 13.893,
          tibetan: "ལེགས་པར་བསམ་ན་སྙིང་ནས་མཆི་མ་འཁྲུགས།",
          phonetics: "LEK PAR SAM NA NYING NÉ CHI MA DRUK",
          english: ["Thinking of this, tears well up from my heart."],
        },
        {
          start: 14.348,
          end: 18.058,
          tibetan: "རང་དབང་རང་གིས་ཐོབ་ཚེ་ཆོས་ལ་འབུང།།",
          phonetics: "RANG WANG RANG GI TOP TSÉ CHÖ LA BUNG",
          english: ["I’ll devote to Dharma this freedom I’ve gained."],
        },
        {
          start: 18.566,
          end: 23.705,
          tibetan: "བསླུ་མེད་དཀོན་མཆོག་གསུམ་ལ་སྐྱབས་སུ་འགྲོ།།",
          phonetics: "LU MÉ KÖN CHOK SUM LA KYAP SU DRO",
          english: ["Trustworthy Three Jewels, I go for refuge to you."],
        },
      ],
    },
    "reflection-six": {
      title: "Sixth Reflection",
      subtitle: "Benefits of liberation",
      sourcePage: "Liturgy page 7 (PDF page 9)",
      status: "Phrase timing derived from pauses; review while listening.",
      phrases: [
        {
          start: 1.09,
          end: 5.95,
          tibetan: "ཚོགས་གཉིས་རྫོགས་པས་རང་གཞན་དོན་གཉིས་འགྲུབ།།",
          phonetics: "TSOK NYI DZOK PÉ RANG SHEN DÖN NYI DRUP",
          english: ["Perfecting the two accumulations", "Brings benefit to me and others as well."],
        },
        {
          start: 6.379,
          end: 10.137,
          tibetan: "བདག་གཞན་མཉམ་པས་དགྲ་གཉེན་ཆགས་སྡང་བྲལ།།",
          phonetics: "DAK SHEN NYAM PÉ DRA NYEN CHAK DANG DREL",
          english: ["Seeing myself and others as equal, I am free", "Of attachment to friends and aversion to enemies."],
        },
        {
          start: 10.618,
          end: 14.35,
          tibetan: "འགྲོ་ཀུན་ཕ་མར་ཤེས་པས་བྱང་སེམས་ལྡན།།",
          phonetics: "DRO KUN PA MAR SHÉ PÉ CHANG SEM DEN",
          english: ["Knowing that all beings have been my parents", "Endows me with bodhichitta."],
        },
        {
          start: 14.912,
          end: 18.689,
          tibetan: "རང་སེམས་རྟོགས་པས་སྣང་བ་ཆོས་སྐུར་འཆར།།",
          phonetics: "RANG SEM TOK PÉ NANG WA CHÖ KUR CHAR",
          english: ["By realizing the nature of mind,", "All appearances dawn as dharmakaya."],
        },
        {
          start: 19.197,
          end: 24.132,
          tibetan: "བདེ་ཆེན་ཐར་པའི་ཕན་ཡོན་བསམ་མི་ཁྱབ།།",
          phonetics: "DÉ CHEN TAR PÉ PEN YÖN SAM MI KYAP",
          english: ["Inconceivable are these benefits", "Of liberation into great bliss."],
        },
      ],
    },
  },
};
